In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
import seaborn as sns
# Importing the required packages 
import pandas as pd 
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [2]:
KDDTrain = pd.read_csv('KDDTest+.csv')
KDDTest = pd.read_csv('KDDTrain+.csv')


In [3]:
mapping = {'ipsweep': 'Probe','satan': 'Probe','nmap': 'Probe','portsweep': 'Probe','saint': 'Probe','mscan': 'Probe',
        'teardrop': 'DoS','pod': 'DoS','land': 'DoS','back': 'DoS','neptune': 'DoS','smurf': 'DoS','mailbomb': 'DoS',
        'udpstorm': 'DoS','apache2': 'DoS','processtable': 'DoS',
        'perl': 'U2R','loadmodule': 'U2R','rootkit': 'U2R','buffer_overflow': 'U2R','xterm': 'U2R','ps': 'U2R',
        'sqlattack': 'U2R','httptunnel': 'U2R',
        'ftp_write': 'R2L','phf': 'R2L','guess_passwd': 'R2L','warezmaster': 'R2L','warezclient': 'R2L','imap': 'R2L',
        'spy': 'R2L','multihop': 'R2L','named': 'R2L','snmpguess': 'R2L','worm': 'R2L','snmpgetattack': 'R2L',
        'xsnoop': 'R2L','xlock': 'R2L','sendmail': 'R2L',
        'normal': 'Normal'
        }

In [4]:
# Apply attack class mappings to the dataset
KDDTrain['attack_class'] = KDDTrain['labels'].apply(lambda v: mapping[v])
KDDTest['attack_class'] = KDDTest['labels'].apply(lambda v: mapping[v])

In [5]:
from sklearn.preprocessing import LabelEncoder
le_protocol = LabelEncoder()
le_service = LabelEncoder()
le_flag = LabelEncoder()
KDDTrain['protocol_type'] = le_protocol.fit_transform(KDDTrain.protocol_type)
KDDTrain['service'] = le_protocol.fit_transform(KDDTrain.service)
KDDTrain['flag'] = le_protocol.fit_transform(KDDTrain.flag)
KDDTrain
KDDTest['protocol_type'] = le_protocol.fit_transform(KDDTest.protocol_type)
KDDTest['service'] = le_protocol.fit_transform(KDDTest.service)
KDDTest['flag'] = le_protocol.fit_transform(KDDTest.flag)

In [6]:
X_train = KDDTrain.iloc[:,0:40]  # All rows, omit last  2 column
y_train = KDDTrain.iloc[:,42]# All rows, only the last column

X_test = KDDTrain.iloc[:,0:40]  # All rows, omit last 2 column
y_test = KDDTrain.iloc[:,42]# All rows, only the last column

#  Predicting class attack

### KNN

In [7]:
from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier()
knn_model.fit(X_train,y_train)
knn_prediction = knn_model.predict(X_test)

In [8]:
print("Accuracy score for KNN:",accuracy_score(y_test,knn_prediction))

Accuracy score for KNN: 0.9764017033356991


#### Predicting the actual labels

In [9]:
X_train = KDDTrain.iloc[:,0:40]  # All rows, omit last 2 columns
y_train = KDDTrain.iloc[:,41]# All rows, only the second last column

X_test = KDDTrain.iloc[:,0:40]  # All rows, omit last 2 column
y_test = KDDTrain.iloc[:,41]# All rows, only the second last  column

### Predicting the actual labels

In [10]:
knn_model = KNeighborsClassifier()
knn_model.fit(X_train,y_train)
knn_prediction = knn_model.predict(X_test)

In [11]:
print("Accuracy score for KNN:",accuracy_score(y_test,knn_prediction))

Accuracy score for KNN: 0.970679559971611


#### SVM

In [17]:
X_train = KDDTrain.iloc[:,0:40]  # All rows, omit last  2 column
y_train = KDDTrain.iloc[:,42]# All rows, only the last column

X_test = KDDTrain.iloc[:,0:40]  # All rows, omit last 2 column
y_test = KDDTrain.iloc[:,42]# All rows, only the last column

#  Predicting class attack

In [18]:

from sklearn.svm import SVC

plf=SVC(random_state=0)

In [19]:
plf.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [20]:
y_pred = plf.predict(X_test)

In [21]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  
print(accuracy_score(y_test, y_pred))

[[ 804 6654    0    0    0]
 [  59 9648    0    4    0]
 [   0 2421    0    0    0]
 [   7 2523    0  224    0]
 [   0  198    0    2    0]]


C:\Users\ninadgorey\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

         DoS       0.92      0.11      0.19      7458
      Normal       0.45      0.99      0.62      9711
       Probe       0.00      0.00      0.00      2421
         R2L       0.97      0.08      0.15      2754
         U2R       0.00      0.00      0.00       200

    accuracy                           0.47     22544
   macro avg       0.47      0.24      0.19     22544
weighted avg       0.62      0.47      0.35     22544

0.4735628105039035


In [22]:
print(accuracy_score(y_test, y_pred))

0.4735628105039035


### Logistic Regression

In [27]:
from sklearn import preprocessing
# Preprocess
enc = preprocessing.OrdinalEncoder()

encoded_dataset = enc.fit_transform(KDDTrain)  # All categorical features are now numerical
X_train = encoded_dataset[:, :-2]  # All rows, omit last column
y_train = np.ravel(encoded_dataset[:, -1:])  # All rows, only the last column

In [28]:
# Repeat preprocessing for test data
encoded_dataset = enc.fit_transform(KDDTest)
X_test = encoded_dataset[:, :-2]
y_test = np.ravel(encoded_dataset[:, -1:])


In [29]:
from sklearn.linear_model import LogisticRegression

In [30]:
clf=LogisticRegression(random_state=0)

clf.fit(X_train, y_train)

C:\Users\ninadgorey\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [31]:
y_pred = clf.predict(X_test)

In [32]:
print(accuracy_score(y_test, y_pred))

0.8473085502448937


In [33]:
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  
print(accuracy_score(y_test, y_pred))

[[42694  2403   777    53     0]
 [ 6058 55592  2541  2953   199]
 [ 1581  1496  7999   506    74]
 [  123   426     6   437     3]
 [    4    24     0     8    16]]
              precision    recall  f1-score   support

         0.0       0.85      0.93      0.89     45927
         1.0       0.93      0.83      0.87     67343
         2.0       0.71      0.69      0.70     11656
         3.0       0.11      0.44      0.18       995
         4.0       0.05      0.31      0.09        52

    accuracy                           0.85    125973
   macro avg       0.53      0.64      0.55    125973
weighted avg       0.87      0.85      0.86    125973

0.8473085502448937
